import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class Global {
  constructor() { }
  public TITLE_NOVEDADES = 'Novedades';
  public TITLE_RECOMENDADOS = 'Recomendados';
  public TITLE_LITERATURA = 'Literatura';
  public TITLE_AUSTRAL = 'Austral';
  public LISTA_LIBROS = {
    "novedades": [
      {
        "titulo": "EL CHICO QUE SIGUIÓ A SU PADRE HASTA AUSCHWITZ",
        "autor": "JEREMY DRONFIELD",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "48.30",
        "precioVenta": "62.10",
        "detalle": "30% DESCUENTOS",
        "imagen": "el-chico-que-siguio-a-su-padre-hasta-auschwitz.jpg",
        "cantidad": 1,
        "filtro": "filter_mayo"
      },
      {
        "titulo": "MIL NOCHES SIN TI",
        "autor": "FEDERICO MOCCIA",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "48.30",
        "precioVenta": "62.10",
        "detalle": "30% DESCUENTOS",
        "imagen": "mil-noches.jpg",
        "cantidad": 1,
        "filtro": "filter_mayo"
      },
      {
        "titulo": "LA SOSPECHA",
        "autor": "FIONA BARTON",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "48.30",
        "precioVenta": "62.10",
        "detalle": "30% DESCUENTOS",
        "imagen": "la-sospecha.jpg",
        "cantidad": 1,
        "filtro": "filter_mayo"
      },
      {
        "titulo": "ESTRATEGIAS CON CALLE",
        "autor": "CRISTINA QUIÑONES",
        "editorial": "Planeta",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "estrategias-con-calle.jpg",
        "cantidad": 1,
        "filtro": "filter_abril"
      },
      {
        "titulo": "DÍAS SIN TI",
        "autor": "ELVIRA SASTRE",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "dias-sin-ti.jpg",
        "cantidad": 1,
        "filtro": "filter_abril"
      },
      {
        "titulo": "LA MUJER SOVIÉTICA",
        "autor": "DANY SALVATIERRA",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "mujer-sovietica.jpg",
        "cantidad": 1,
        "filtro": "filter_abril"
      },
      {
        "titulo": "FILOSOFÍA EN 11 FRASES",
        "autor": "DARIO SZTAJNSZRAJBER",
        "editorial": "Paidós",
        "precioOriginal": "59.00",
        "precioCompra": "39.34",
        "precioVenta": "53.10",
        "detalle": "oferta 3 x 2",
        "imagen": "filosofia-11-frases.jpg",
        "cantidad": 1,
        "filtro": "filter_abril"
      },
      {
        "titulo": "EL PUZZLE DE CRISTAL",
        "autor": "BLUE JEANS",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "puzle-cristal.jpg",
        "cantidad": 1,
        "filtro": "filter_marzo"
      },
      {
        "titulo": "LA MUERTE DEL COMENDADOR 2",
        "autor": "HARUKI MURAKAMI",
        "editorial": "Tusquets",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "muerte-comendador-2.jpg",
        "cantidad": 1,
        "filtro": "filter_marzo"
      }
    ],
    "recomendados": [
      {
        "titulo": "YO JULIA",
        "autor": "SANTIAGO POSTERGUILLO",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "yo-julia.jpg",
        "cantidad": 2,
        "filtro": ""
      },
      {
        "titulo": "HOMO DEUS",
        "autor": "YUVAL NOAH HARARI",
        "editorial": "Debate",
        "precioOriginal": "89.00",
        "precioCompra": "59.34",
        "precioVenta": "80.10",
        "detalle": "oferta 3 x 2",
        "imagen": "homo-deus.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "POESÍA COMPLETA",
        "autor": "CESAR VALLEJO",
        "editorial": "Seix Barral",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "poesia-completa.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "UNA NOVELA CRIMINAL",
        "autor": "JORGE VOLPI",
        "editorial": "Alfaguara",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "novela-criminal.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "SÁLVESE QUIEN PUEDA",
        "autor": "ANDRÉS OPPENHEIMER",
        "editorial": "Debate",
        "precioOriginal": "89.00",
        "precioCompra": "59.34",
        "precioVenta": "80.10",
        "detalle": "oferta 3 x 2",
        "imagen": "salvese-quien-pueda.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "RENDICIÓN",
        "autor": "RAY LORIGA",
        "editorial": "Alfaguara",
        "precioOriginal": "59.00",
        "precioCompra": "39.34",
        "precioVenta": "53.10",
        "detalle": "oferta 3 x 2",
        "imagen": "rendicion.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "21 LECCIONES PARA EL SIGLO XXI",
        "autor": "YUVAL NOAH HARARI",
        "editorial": "Debate",
        "precioOriginal": "89.00",
        "precioCompra": "59.34",
        "precioVenta": "80.10",
        "detalle": "oferta 3 x 2",
        "imagen": "21-lecciones-siglo-xxi.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "CANCIÓN DE HIELO Y FUEGO",
        "autor": "GEORGE R. R. MARTIN",
        "editorial": "DeBolsillo",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "cancion-hielo-fuego-1.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ELON MUSK",
        "autor": "ASHLEE VANCE",
        "editorial": "Vergara",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "elon-musk.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "STEVE JOBS",
        "autor": "KAREN BLUMENTHAL",
        "editorial": "Altea",
        "precioOriginal": "59.00",
        "precioCompra": "39.34",
        "precioVenta": "53.10",
        "detalle": "oferta 3 x 2",
        "imagen": "steve-jobs.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "MIENTRAS ESCRIBO",
        "autor": "STEPHEN KING",
        "editorial": "DeBolsillo",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "mientras-escribo.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "MIEDO",
        "autor": "BOB WOODWARD",
        "editorial": "Roca",
        "precioOriginal": "89.00",
        "precioCompra": "59.34",
        "precioVenta": "80.10",
        "detalle": "oferta 3 x 2",
        "imagen": "miedo-trump-casa-blanca.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "PADRE RICO PADRE POBRE",
        "autor": "ROBERT KIYOSAKI",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "padre-rico-padre-pobre.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "PIENSE Y HAGASE RICO",
        "autor": "NAPOLEON HILL",
        "editorial": "DeBolsillo",
        "precioOriginal": "39.00",
        "precioCompra": "26.00",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "piense-hagase-rico.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ACTITUD MENTAL POSITIVA",
        "autor": "NAPOLEON HILL",
        "editorial": "DeBolsillo",
        "precioOriginal": "39.00",
        "precioCompra": "26.00",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "actitud-mental-positiva.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "MUCHAS VIDAS MUCHOS MAESTROS",
        "autor": "BRIAN WEISS",
        "editorial": "B de Bolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "muchas-vidas-muchos-maestros.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "CHARLAS TED",
        "autor": "CHRIS ANDERSON",
        "editorial": "New York Times",
        "precioOriginal": "59.00",
        "precioCompra": "39.34",
        "precioVenta": "53.10",
        "detalle": "oferta 3 x 2",
        "imagen": "charlas-ted.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL CAMINO HACIA EL LEAN STARTUP",
        "autor": "ERIC RIES",
        "editorial": "DeBolsillo",
        "precioOriginal": "59.00",
        "precioCompra": "39.34",
        "precioVenta": "53.10",
        "detalle": "oferta 3 x 2",
        "imagen": "camino-hacia-lean-startup.jpg",
        "cantidad": 1,
        "filtro": ""
      }
    ],
    "literatura": [
      {
        "titulo": "MITOS, LEYENDAS Y CUENTOS PERUANOS",
        "autor": "JOSÉ MARÍA ARGUEDAS",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "mitos-leyendas.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ABRIL ROJO",
        "autor": "SANTIAGO RONCAGLIOLO",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "abril-rojo.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "COSAS QUE NO HAY QUE CONTAR",
        "autor": "RENATO CISNEROS",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "cosas-no-contar.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ABRAHAM VALDELOMAR",
        "autor": "SELECCIÓN VALDELOMAR",
        "editorial": "EstruendoMudo",
        "precioOriginal": "29.00",
        "precioCompra": "19.34",
        "precioVenta": "26.10",
        "detalle": "oferta 3 x 2",
        "imagen": "valdelomar.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA GUERRA NO TIENE ROSTRO DE MUJER",
        "autor": "STEVLANA ALEXIEVICH",
        "editorial": "Debate",
        "precioOriginal": "89.00",
        "precioCompra": "59.34",
        "precioVenta": "80.10",
        "detalle": "oferta 3 x 2",
        "imagen": "guerra-no-tiene-rostro-mujer.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "SIDDARTHA",
        "autor": "HESSE",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "siddhartha.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "DESGRACIA",
        "autor": "COETZEE",
        "editorial": "DeBolsillo",
        "precioOriginal": "39.00",
        "precioCompra": "26.00",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "desgracia.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA BAILARINA DE AUSCHWITZ",
        "autor": "EDITH EGER",
        "editorial": "Planeta",
        "precioOriginal": "59.00",
        "precioCompra": "41.30",
        "precioVenta": "53.10",
        "detalle": "30% DESCUENTOS",
        "imagen": "la-bailarina-de-auschwitz.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA CHICA INVISIBLE",
        "autor": "BLUE JEANS",
        "editorial": "Planeta",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "chica-invisible.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA MUERTE DEL COMENDADOR",
        "autor": "HARUKI MURAKAMI",
        "editorial": "Tusquets",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "muerte-comendador-1.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "BAILA, BAILA, BAILA",
        "autor": "HARUKI MURAKAMI",
        "editorial": "Tusquets",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "baila-baila-baila.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "PATRIA",
        "autor": "FERNANDO ARAMBURO",
        "editorial": "Tusquets",
        "precioOriginal": "89.00",
        "precioCompra": "59.34",
        "precioVenta": "80.10",
        "detalle": "oferta 3 x 2",
        "imagen": "patria.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "1984",
        "autor": "GEORGE ORWELL",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "1984.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "FICCIONES",
        "autor": "BORGES",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "ficciones.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "BESTIARIO",
        "autor": "JULIO CORTAZAR",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "bestiario.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "MISERY",
        "autor": "STEPHEN KING",
        "editorial": "DeBolsillo",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "misery.jpg",
        "cantidad": 1,
        "filtro": ""
      },

      {
        "titulo": "EL VIEJO Y EL MAR",
        "autor": "ERNEST HEMINGWAY",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "viejo-y-mar.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ASESINATO EN EL ORIENTE EXPRESS",
        "autor": "AGATHA CHRISTIE",
        "editorial": "Booket",
        "precioOriginal": "29.00",
        "precioCompra": "19.34",
        "precioVenta": "26.10",
        "detalle": "oferta 3 x 2",
        "imagen": "asesinato-orient-express.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ALICIA EN EL PAÍS DE LAS MARAVILLAS",
        "autor": "LEWIS CARROLL",
        "editorial": "Penguin Clásicos",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "alicia-pais-maravillas.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL GRAN GATSBY",
        "autor": "SCOTT FITZGERALD",
        "editorial": "Origo",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "gran-gatsby-origo.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL HOMBRE ILUSTRADO",
        "autor": "RAY BRADBURY",
        "editorial": "Booket",
        "precioOriginal": "39.00",
        "precioCompra": "26.00",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "hombre-ilustrado.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL GRAN GATSBY",
        "autor": "SCOTT FITZGERALD",
        "editorial": "DeBolsillo",
        "precioOriginal": "39.00",
        "precioCompra": "26.00",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "gran-gatsby-bolsillo.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "FAHRENHEIT 451",
        "autor": "RAY BRADBURY",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "fahrenheit.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "DIARIO",
        "autor": "ANNA FRANK",
        "editorial": "DeBolsillo",
        "precioOriginal": "39.00",
        "precioCompra": "26.00",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "diario-ana-frank.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ROBINSON CRUSOE",
        "autor": "DANIEL DEFOE",
        "editorial": "DeBolsillo",
        "precioOriginal": "39.00",
        "precioCompra": "27.34",
        "precioVenta": "35.10",
        "detalle": "oferta 3 x 2",
        "imagen": "robinson-crusoe.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "MUJERCITAS",
        "autor": "LOUISA MAY ALCOTT",
        "editorial": "Penguin Clásicos",
        "precioOriginal": "69.00",
        "precioCompra": "46.00",
        "precioVenta": "62.10",
        "detalle": "oferta 3 x 2",
        "imagen": "mujercitas.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL HOBBIT",
        "autor": "J. R. R. TOLKIEN",
        "editorial": "Booket",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "hobbit.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "CUENTOS DE BUENAS NOCHES PARA NIÑAS REBELDES 2",
        "autor": "ELENA FAVILLI",
        "editorial": "Planeta",
        "precioOriginal": "59.00",
        "precioCompra": "39.34",
        "precioVenta": "53.10",
        "detalle": "oferta 3 x 2",
        "imagen": "cuentos-de-buenas-noches-2.jpg",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "CAMBIO DE PALABRAS",
        "autor": "CESAR HILDEBRANDT",
        "editorial": "Planeta",
        "precioOriginal": "49.00",
        "precioCompra": "32.67",
        "precioVenta": "41.10",
        "detalle": "oferta 3 x 2",
        "imagen": "cambio-palabras.jpg",
        "cantidad": 1,
        "filtro": ""
      }
    ],
    "austral": [
      {
        "titulo": "DRÁCULA",
        "autor": "BRAM STOKER",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "dracula2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA ODISEA",
        "autor": "HOMERO",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "la-odisea2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA CASA DE LOS ESPÍRITUS",
        "autor": "ISABEL ALLENDE",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "la-casa-espiritus2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA ILIADA",
        "autor": "HOMERO",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "la-iliada2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ROMEO Y JULIETA",
        "autor": "SHAKESPEARE",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "romeo-y-julieta2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "ORGULLO Y PREJUICIO",
        "autor": "JANE AUSTEN",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "orgullo-y-prejuicio2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "CUENTOS",
        "autor": "ALLAN POE",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "cuentos2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LOS CACHORROS",
        "autor": "VARGAS LLOSA",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "los-cachorros2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL PERFUME",
        "autor": "SUSKIND",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "el-perfume2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "EL RETRATO DE DORIAN GREY",
        "autor": "OSCAR WILDE",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "el-retrato-dorian-grey2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "FRANKEINSTEIN",
        "autor": "SHELLEY",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "frankenstein2.png",
        "cantidad": 1,
        "filtro": ""
      },
      {
        "titulo": "LA METAMORFÓSIS",
        "autor": "KAFKA",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "",
        "cantidad": 0,
        "filtro": ""
      },
      {
        "titulo": "BODA DE SANGRE",
        "autor": "GARCIA LORCA",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "",
        "cantidad": 0,
        "filtro": ""
      },
      {
        "titulo": "VEINTE POEMAS DE AMOR Y UNA CANCIÓN DESESPERADA",
        "autor": "NERUDA",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "",
        "cantidad": 0,
        "filtro": ""
      },
      {
        "titulo": "EL TÚNEL",
        "autor": "SABATO",
        "editorial": "Austral",
        "precioOriginal": "19.90",
        "precioCompra": "19.00",
        "precioVenta": "19.90",
        "detalle": "",
        "imagen": "el-tunel2.png",
        "cantidad": 0,
        "filtro": ""
      }
    ],
    "otros": [
      {
        "titulo": "EL MONJE QUE VENDIÓ SU FERRARI",
        "autor": "ROBIN S. SHARMA",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "monje-que-vendio-su-ferrari.jpg",
        "cantidad": 0,
        "filtro": ""
      },
      {
        "titulo": "SABIDURÍA COTIDIANA",
        "autor": "ROBIN S. SHARMA",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "sabiduria-cotidiana-monje.jpg",
        "cantidad": 0,
        "filtro": ""
      },
      {
        "titulo": "DESCUBRE TU DESTINO",
        "autor": "ROBIN S. SHARMA",
        "editorial": "DeBolsillo",
        "precioOriginal": "35.00",
        "precioCompra": "23.34",
        "precioVenta": "31.50",
        "detalle": "oferta 3 x 2",
        "imagen": "descubre-tu-destino.jpg",
        "cantidad": 0,
        "filtro": ""
      }
    ]
  }




}
